# $Id: radioactive.mac 74917 2013-10-24 10:44:43Z ihrivnac $
#
#
/control/verbose 2
/run/verbose 2
#
/testhadr/det/setNbOfAbsor  1
#/testhadr/det/setAbsor 1 LaBr3_Ce 3.81 cm
/testhadr/det/setAbsor 1 LaBr3 3.81 cm
/testhadr/det/setSizeYZ  3.81 cm
#
/run/initialize
#
/testhadr/gun/setDefault
/gun/particle neutron
#/gun/ion 11 22
/gun/energy 14.1 MeV
/gun/position 0 -38.5 0 cm
#
/analysis/setFileName SABAT
/analysis/h1/set 1 290 0. 14.5 MeV	#edep of Gamma
/analysis/h1/setAscii 1
/analysis/h1/set 2 290 0. 14.5 MeV	#ekin of Gamma
/analysis/h1/setAscii 2
/analysis/h1/set 3 290 0. 14.5 MeV	#ekin of Neutrons
/analysis/h1/setAscii 3
/analysis/h1/set 4 290 0. 14.5 MeV	#ekin of Neutrons generated in Detector
/analysis/h1/setAscii 4
/run/printProgress 1000000
#
/run/beamOn 5000000
